### ISSUE TITLE
NextGen and Post Snippets conflict

### ISSUE THREAD

**Issue by artstorm** [artstorm/post-snippets#34]
Hallo, I found quite an annoying compatibility issue.

I use WP v.3.8.1, NextGen v.2.0.40 and Post Snippets v.2.3.2
Unfortunately, I can't edit thumbnails in NextGen
(when I try to do it, popup window to edit a thumbnail is not active).
When I deactivate Post Snippets, the problem with NextGen disappears.

It would be nice, if you could help with it. Thank you.

https://wordpress.org/plugins/post-snippets/

From: http://wordpress.org/support/topic/nextgen-and-post-snippets-conflict?replies=1

**Comment by KZeni** [comment]
I think I resolved this by fixing a conflict this plugin had with Download Monitor (was causing JavaScript error in editor popup). I've submitted a pull request: https://github.com/artstorm/post-snippets/pull/56

Here's a direct link to my modified `src/PostSnippets/WPEditor.php` file for Post Snippets 2.5 to fix that plugin conflict: https://raw.githubusercontent.com/artstorm/post-snippets/72aade45bda47785ee95239bac1f4b2a1bef416e/src/PostSnippets/WPEditor.php (assuming it's the same issue I was having)

**Comment by artstorm** [comment]
Should be fixed by PR #56
