### ISSUE TITLE
Enqueue admin JS only on plugin admin pages

### ISSUE THREAD

**Issue by pderksen** [artstorm/post-snippets#45]
The admin settings page JS is unfortunately causing conflicts on other plugin settings pages, such as Gravity Forms (the search & filtering of form entries in the admin most notably).

![image](https://cloud.githubusercontent.com/assets/79667/10891216/6d0fae48-8151-11e5-9644-a5da31b349d4.png)

![image](https://cloud.githubusercontent.com/assets/79667/10891199/5ced304e-8151-11e5-9fc4-a10770630dca.png)

Could the enqueue scripts be update to include only on this plugin's settings pages? There's a [great tutorial here](https://pippinsplugins.com/loading-scripts-correctly-in-the-wordpress-admin/) (at the very end is this specific issue).

Thanks for the great plugin!

**Comment by artstorm** [comment]
@pderksen Thanks for the issue. I'll definitely look into this for the next update.

**Comment by pderksen** [comment]
@artstorm Awesome thanks!

**Comment by pderksen** [comment]
@artstorm Tested out Gravity Forms entries in my admin and no more JS conflicts. Thanks!
